# General site information
site_name: CyVerse Learning Home
site_description: Documentation for CyVerse Platforms and Education
site_author: CyVerse Science Team
site_url: https://learning.cyverse.org

# Repository information
repo_name: CyVerse-learning-materials/learning-materials-home
repo_url: https://github.com/CyVerse-learning-materials/learning-materials-home
edit_uri: edit/main/docs

# Footer
copyright: 'Copyright &copy; 2024 CyVerse'

# Navigation Page (merging both sets of navigation items)
nav:
  - 'Home':
    - index.md
    - 'What is CyVerse?': what_is_cyverse.md
    - 'Self-Guided Tour': mooc.md
    - 'Set Up an Account': account.md
    - 'Getting Help': getting_help.md
  - 'Manage Your Data':
    - ds/index.md
    - 'Moving Data':
      - ds/move_data/index.md
      - 'Data Management with Discovery Environment': de/manage_data.md
      - 'Transferring Data with Cyberduck': ds/cyberduck.md
      - 'Transferring Data with iCommands and Command Line': ds/icommands.md
      - 'Transferring Data with GoCommands and Command Line': ds/gocommands.md
      - 'HTTP Access with WebDAV': ds/webdav.md
      - 'Transferring Data with SFTP': ds/sftp.md
    - 'Adding Metadata': ds/metadata.md
    - 'Sharing Data': ds/share.md
    - 'Getting a DOI': ds/doi.md
    - 'Checking Data Storage': ds/check_data.md
    - 'Teams': ds/teams.md
  - 'Run Analyses':
    - de/index.md
    - 'Logging In': de/login.md
    - 'Using Apps': de/using_apps.md
    - 'Managing Analyses': de/managing_analyses.md
    - 'Interactive Analysis': vice/about.md
    - 'Sharing and Using Bags': de/bags.md
  - 'Quick Starts':
    - 'RStudio in 6 steps': vice/quick-rstudio.md
    - 'JupyterLab in 6 steps': vice/quick-jupyter.md
    - 'Cloud Shell in 6 steps': vice/quick-cloudshell.md
    - 'Distributing Data in 6 steps': ds/quick-data-share.md
    - 'Sharing Apps Quick Start': vice/quick-app-launch.md
    - 'Access Data in VICE Apps': vice/csi.md  
  - 'Cloud Services':
    - cloud/index.md
  - 'Analyze Images':
    - bisque/index.md
  - 'For the Classroom':
    - 'Teach using CyVerse': vice/teaching.md
    - 'DNA Subway': dna_subway_guide.md
  - 'Develop':
    - 'Integrate Apps and Tools': de/create_apps.md
    - 'Interactive Apps': vice/extend_apps.md
    - 'Powered by CyVerse': powered_by.md
    - 'Developer Manuals': manuals.md
  - 'Science Tutorials':
    - tutorials/index.md
  - 'CyVerse Workshops':
    - workshops/index.md
    - 'Container Camp': workshops/container_camp.md
    - 'Foundational Open Science Skills': workshops/foss.md
  - 'Reference':
    - 'Glossary': glossary.md
    - 'FAQ': faq.md

# Theme settings
theme:
  name: material
  palette:
    # Light mode settings
    - media: "(prefers-color-scheme: light)"
      primary: '#002E99'
      accent: 'orange'
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode settings
    - media: "(prefers-color-scheme: dark)"
      primary: '#002E99'
      accent: 'orange'
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: 'Roboto Mono'
  favicon: 'assets/favicon.ico'
  logo: 'assets/android-chrome-512x512.png'
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - toc.follow
    - content.code.copy
    - palette.toggle

# Analytics and social links
extra:
  social:
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/
    - icon: fontawesome/brands/github
      link: https://github.com/cyverse-learning-materials/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/cyverseorg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/cyverse.org
    - icon: fontawesome/brands/docker
      link: https://harbor.cyverse.org/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/CyverseOrgProject
  analytics:
    provider: google
    property: UA-72224033-6

# Extra CSS and JavaScript (added chatbot)
extra_css:
  - stylesheets/extra.css
  - chatbot_widget.css

extra_javascript:
  - chatbot_widget.js

# Markdown Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search
  - mkdocstrings
  - git-revision-date
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True
